# Prepare

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
df_rating = pd.read_csv("../imdb/title.ratings.tsv", sep='\t')
df_basics = pd.read_csv("../imdb/title.basics.tsv", sep='\t')

In [17]:
DISNEY_COLORS = {
    "blue": "#393e8f",
    "yellow":"#f3cc64",
    "red":"#b12228",
    "pink":"#efbeb7",
    "white":"#ffffff",
    "blue_oxford":"#12194a",
    }

# Wrangling

The following code snippet performs data manipulation on a pandas DataFrame named `df_basics`. The purpose of these operations is to refine the dataset by extracting relevant film types and filtering out undesired genres and title types.

In [18]:
df_basics["type_film"] = df_basics["genres"].str.split(",").str[0]
df_basics = df_basics[~df_basics["type_film"].isin(["Documentary", "Short", "News", "Talk-Show", "Game-Show", "Reality-TV"])]
df_basics = df_basics[df_basics["titleType"].isin(["movie", "tvSeries", "tvMovie"])]
df_basics["titleType"].unique()

array(['movie', 'tvMovie', 'tvSeries'], dtype=object)

In [19]:
# There are some titles that are repeated because there are different products associated to it.
# Then I will take care of it.

df_basics[df_basics["primaryTitle"] == "Hercules"]

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,type_film
49470,tt0050381,movie,Hercules,Le fatiche di Ercole,0,1958,\N,107,"Adventure,Fantasy,History",Adventure
83786,tt0085672,movie,Hercules,Hercules,0,1983,\N,98,"Adventure,Fantasy,History",Adventure
116466,tt0119282,movie,Hercules,Hercules,0,1997,\N,93,"Action,Adventure,Animation",Action
134887,tt0138967,tvSeries,Hercules,Hercules,0,1998,1999,30,"Action,Adventure,Animation",Action
169604,tt0175729,movie,Hercules,Hercules,0,1964,\N,142,Adventure,Adventure
438625,tt0456974,tvMovie,Hercules,Hercules,0,2005,\N,190,"Drama,Musical",Drama
816574,tt0843514,movie,Hercules,Hercules,0,1953,\N,\N,"Action,Adventure,Fantasy",Action
2435642,tt1267297,movie,Hercules,Hercules,0,2014,\N,98,"Action,Adventure,Fantasy",Action
5347058,tt21068738,movie,Hercules,Hercules,0,\N,\N,\N,"Action,Adventure,Comedy",Action
8469920,tt3985956,movie,Hercules,Hercules,0,2014,\N,112,Comedy,Comedy
8914625,tt4991366,tvMovie,Hercules,Hercules,0,1998,\N,89,Animation,Animation

In [20]:
df_disney = pd.read_excel("../table_a.xlsx") # import TABLE_A. 

#transform watch length from ms to min and create a "title_name" that is the "program_full_title" if it is a movie, "series_full_title" if not
df_disney['WATCH_LENGTH_MIN'] = df_disney['WATCH_LENGTH_MS'] / 60000 #originally in miliseconds
df_disney['title_name'] = np.where(df_disney['PROGRAM_TYPE'] == 'movie', 
                               df_disney['PROGRAM_FULL_TITLE'], 
                               df_disney['SERIES_FULL_TITLE'])
df_disney

,PROGRAM_ID,SERIES_ID,SEASON_ID,ACCOUNT_ID,START_DATE_EST,END_DATE_EST,ACCOUNT_HOME_COUNTRY,PROGRAM_FULL_TITLE,SEASON_FULL_TITLE,SERIES_FULL_TITLE,PROGRAM_TYPE,SEASON_NUMBER,EPISODE_SEQUENCE_NUMBER,EPISODE_SERIES_SEQUENCE_NUMBER,RUNTIME,WATCH_LENGTH_MS,IS_STREAM,IS_COMPLETED_STREAM,WATCH_LENGTH_MIN,title_name
0,fre123-34534,jlk456-nm-56,tre-765-fd,jewq345-b3,2021-01-01,2021-01-01,MX,Chapter 9: The Marshall,The Mandalorian Season 2,The Mandalorian,episode,2,1,9,3244,167251,1,0,2.787517,The Mandalorian
1,qwe-567-dsa,jlk456-nm-56,hjfg-123-re,asd-345-h,2021-06-06,2021-06-06,BR,Chapter 1: The Mandalorian,The Mandalorian Season 1,The Mandalorian,episode,1,1,1,2377,30005,1,0,0.500083,The Mandalorian
2,mrvl-456-tre,NaN,NaN,asd-345-h,2021-06-15,2021-06-15,MX,Ice Age: Dawn Of The Dinosaurs,NaN,NaN,movie,0,0,0,5797,4620000,1,1,77.000000,Ice Age: Dawn Of The Dinosaurs
3,2b81a,NaN,NaN,43116,2021-06-16,2021-06-16,BR,Snow White and The Seven Dwarfs,NaN,NaN,movie,0,0,0,5077,0,0,0,0.000000,Snow White and The Seven Dwarfs
4,8a0f2,886E-,51B3-,41d0c,2021-06-11,2021-06-11,MX,Alexs Choice,Wizards of Waverly Place,Wizards of Waverly Place,episode,1,7,7,1443,922667,1,1,15.377783,Wizards of Waverly Place
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,40728,NaN,NaN,00d2d,2021-07-01,2021-07-01,MX,Toy Story 2,NaN,NaN,movie,0,0,0,5574,3997529,1,0,66.625483,Toy Story 2
210,afe43,CCD9-,E177-,76671,2021-06-04,2021-06-04,MX,Mickey Goes Fishing,Mickey Mouse Clubhouse,Mickey Mouse Clubhouse,episode,1,5,5,1535,1290573,1,1,21.509550,Mickey Mouse Clubhouse
211,c5344,NaN,NaN,44d07,2021-06-21,2021-06-21,BR,Newsies Clip,NaN,NaN,promotional,0,0,0,65,66253,1,1,1.104217,NaN
212,d1797,NaN,NaN,78625,2021-06-04,2021-06-04,AR,Loki Trailer,NaN,NaN,promotional,0,0,0,136,119966,1,1,1.999433,NaN
213,74eff,NaN,NaN,975d2,2021-06-01,2021-06-01,MX,Pirates of the Caribbean: Dead Men Tell No Tales,NaN,NaN,movie,0,0,0,7744,2973761,1,0,49.562683,Pirates of the Caribbean: Dead Men Tell No Tales

In [21]:
# Merge the disney data with the basic data from IMDB

df_disney = df_disney.merge(df_basics[["tconst", "primaryTitle"]], 
                            left_on="title_name", 
                            right_on="primaryTitle", 
                            how="left")

# Merge the disney data (included the basic data from IMDB) with the rating data to get averageRating, numVotes, and tconst from IMDB
df_disney = df_disney.merge(df_rating[["averageRating", "numVotes", "tconst"]], 
                            how="left", 
                            on="tconst")

df_disney = df_disney.dropna(subset=['numVotes'])

# Group by 'title_name' and keep only the row with the highest 'numVotes'
# This avoids the repetition. I assume that Disney has the most voted for the title. 
df_disney = df_disney.loc[df_disney.groupby('title_name')['numVotes'].idxmax()]

df_disney = df_disney[["title_name", "PROGRAM_TYPE","averageRating", "WATCH_LENGTH_MIN", "numVotes"]].dropna()

#get the main statistics for each product. 
df_disney = df_disney.groupby(["title_name"], as_index=False).agg({"PROGRAM_TYPE":"first","averageRating":"first", "WATCH_LENGTH_MIN":"sum", "numVotes":"first"})

df_disney

,title_name,PROGRAM_TYPE,averageRating,WATCH_LENGTH_MIN,numVotes
0,Agent Carter,episode,7.8,40.697067,90240.0
1,Agents of S.H.I.E.L.D.,episode,7.5,42.507550,227859.0
2,Aladdin,movie,8.0,0.147700,477439.0
3,Amphibia,episode,8.3,6.758500,9656.0
4,Austin & Ally,episode,6.0,22.507267,13587.0
...,...,...,...,...,...
70,Violetta,episode,5.4,41.733100,2952.0
71,While You Were Sleeping,movie,6.8,32.258367,116060.0
72,Wizards of Waverly Place,episode,6.9,15.377783,39213.0
73,X-Men,episode,7.3,0.616067,661803.0
74,Zenimation,episode,7.4,4.977000,521.0

In [23]:
# Mapping program types, only for readability
df_disney['program_type_legend'] = df_disney['PROGRAM_TYPE'].replace({'episode': 'Series', 'movie': 'Movie'})

# Find the product with the highest and lowest IMDB ratings, and highest watch length
highest_rating = df_disney.loc[df_disney['averageRating'].idxmax()]
lowest_rating = df_disney.loc[df_disney['averageRating'].idxmin()]
highest_watch_length = df_disney.loc[df_disney['WATCH_LENGTH_MIN'].idxmax()]

# Create the scatter plot
fig = px.scatter(
    df_disney, 
    x='averageRating', 
    y='WATCH_LENGTH_MIN', 
    hover_data=['title_name'],  # Include title in hover info
    color='program_type_legend',  # Color based on program_type_legend
    color_discrete_map={'Series': DISNEY_COLORS['blue'], 'Movie': DISNEY_COLORS['yellow']},  # Map Disney colors
    # trendline='ols',  # Add linear regression line
    title='<b>IMDB Average Ratings vs Watch Length of Disney Products',
    labels={
        'averageRating': 'IMDB Average Rating',
        'WATCH_LENGTH_MIN': 'Watch Length (Minutes)',
        'title_name': "Name of the title",
        'program_type_legend': 'Program Type'
    }
)

# Add annotation for the highest and lowest IMDB ratings, and highest watch length
fig.add_annotation(
    x=highest_rating['averageRating'], 
    y=highest_rating['WATCH_LENGTH_MIN'],
    text=f"Highest Rated: {highest_rating['title_name']}",
    showarrow=True,
    arrowhead=2,
    ax=0,
    ay=-50,
    font=dict(color="green", size=12)  # Using yellow from palette
)

fig.add_annotation(
    x=lowest_rating['averageRating'], 
    y=lowest_rating['WATCH_LENGTH_MIN'],
    text=f"Lowest Rated: {lowest_rating['title_name']}",
    showarrow=True,
    arrowhead=2,
    ax=0,
    ay=50,
    font=dict(color=DISNEY_COLORS['red'], size=12)  # Using red from palette
)

fig.add_annotation(
    x=highest_watch_length['averageRating'], 
    y=highest_watch_length['WATCH_LENGTH_MIN'],
    text=f"Longest Watch: {highest_watch_length['title_name']}",
    showarrow=True,
    arrowhead=2,
    ax=0,
    ay=-50,
    font=dict(color=DISNEY_COLORS['blue_oxford'], size=12)  # Using blue_oxford from palette
)

# Update the layout to include font, title, and axis titles
fig.update_layout(
    font_family='Helvetica',  # Change font to Helvetica
    xaxis_title='IMDB Average Rating',
    yaxis_title='Watch Length (Minutes)',
    title_x=0.5,  # Center the title
    height=500,
    width=800,
    legend_title_text='Program Type',  # Set legend title
    legend=dict(
        x=0.01, y=0.99,  # Positioning legend at top-left corner
        bgcolor='rgba(255,255,255,0.6)',  # Background color for readability
    )
)

fig.update_layout(template = None)